### ISSUE TITLE
Плагин создаёт ошибку 500

### ISSUE THREAD

**Issue by pipneogen** [southbridgeio/redmine_issue_open_date#18]
Использую:
`4.9.0-11-amd64 #1 SMP Debian 4.9.189-3 (2019-09-02) x86_64 GNU/Linux`
**Environment:**
  Redmine version                3.4.11.stable
  Ruby version                   2.4.6-p354 (2019-04-01) [x86_64-linux]
  Rails version                  4.2.11.1
  Environment                    production
  Database adapter               Mysql2
**SCM:**
  Subversion                     1.9.5
  Git                            2.11.0
  Filesystem                     
**Redmine plugins:**
  a_common_libs                  2.5.3
  accept                         0.0.2
  redmine_auto_percent           0.0.1
  redmine_checklists             3.1.16
  redmine_contacts               4.2.5
  redmine_contacts_invoices      4.2.0
  redmine_drafts                 0.2.0
  redmine_finance                2.1.6
  redmine_issue_tabs             1.3.2
  redmine_issues_hub             0.0.2
  redmine_people                 1.4.1
  redmine_wikicipher             0.0.10
  redmineup_tags                 2.0.8
  unread_issues                  2.2.3
  usability                      2.3.9

Когда я устанавливаю данный плагин и выполняю миграцию - любые изменения задач и создание новых ломается и появляется ошибка 500 internal server error.
При этом в production.log , логе nginx - ничего не отображается.

Используется веб сервер nginx + passenger

**Comment by olemskoi** [comment]
В списке плагинов нет redmine_issue_open_date
Вы уверены, что ничего не перепутали?

**Comment by pipneogen** [comment]
Я его удалил, так как он мешал работе системы. Сейчас я поставил снова, 
могу прислать актуальные данные.


13 Nov 2019 21:33, Igor Olemskoi пишет:

**Comment by olemskoi** [comment]
Попробуйте убрать другие плагины и добавлять их постепенно. Методом исключения найдите конфликтующий плагин.

Или добейтесь, чтобы в логах выводилась отладочная информация и отправьте ее в тикет.

**Comment by pipneogen** [comment]
Я удалил все плагины из системы и оставил только redmine_issue_open_data.

Проблема сохранилось. Вот кусок production.log после попытки перевести 
задачу в "замороженный" статус:

    /Started PATCH "/issues/174/edit.js" for 212.58.119.238 at
    2019-11-13 21:55:10 +0400//
    //Processing by IssuesController#edit as JS//
    //  Parameters: {"utf8"=>"✓",
    "authenticity_token"=>"KTMNasXn1nNlSesyZ4u0XSMCMwf5jhu27tadco9pvH6g0ZbVKHggZhXCRjprNc92ILI3vKz8VFSkqTSm20dewg==",
    "form_update_triggered_by"=>"issue_status_id",
    "issue"=>{"is_private"=>"0", "project_id"=>"10", "tracker_id"=>"4",
    "subject"=>"Create wiki for All projects", "description"=>"",
    "status_id"=>"15", "priority_id"=>"12", "assigned_to_id"=>"5",
    "parent_issue_id"=>"", "start_date"=>"2018-05-21",
    "estimated_hours"=>"12:00", "notes"=>"", "private_notes"=>"0",
    "lock_version"=>"7"}, "time_entry"=>{"hours"=>"",
    "activity_id"=>"19", "comments"=>""}, "last_journal_id"=>"954",
    "next_issue_id"=>"116", "issue_position"=>"1", "issue_count"=>"6",
    "id"=>"174"}//
    //  Current user: i.pushkin (id=5)//
    //  Rendered issues/_form_custom_fields.html.erb (0.0ms)//
    //  Rendered issues/_attributes.html.erb (11.3ms)//
    //  Rendered
    plugins/redmine_issue_open_date/app/views/issues/_open_date_field.html.erb
    (3.3ms)//
    //  Rendered issues/_form.html.erb (20.7ms)//
    //  Rendered issues/edit.js.erb (21.8ms)//
    //Completed 200 OK in 74ms (Views: 21.0ms | ActiveRecord: 8.6ms)//
    //Started PATCH "/issues/174" for 212.58.119.238 at 2019-11-13
    21:55:17 +0400//
    //Processing by IssuesController#update as HTML//
    //  Parameters: {"utf8"=>"✓",
    "authenticity_token"=>"KTMNasXn1nNlSesyZ4u0XSMCMwf5jhu27tadco9pvH6g0ZbVKHggZhXCRjprNc92ILI3vKz8VFSkqTSm20dewg==",
    "form_update_triggered_by"=>"", "issue"=>{"is_private"=>"0",
    "project_id"=>"10", "tracker_id"=>"4", "subject"=>"Create wiki for
    All projects", "description"=>"", "status_id"=>"15",
    "priority_id"=>"12", "assigned_to_id"=>"5", "parent_issue_id"=>"",
    "start_date"=>"2018-05-21", "estimated_hours"=>"12:00",
    "open_date(3i)"=>"14", "open_date(2i)"=>"11",
    "open_date(1i)"=>"2019", "open_date(4i)"=>"06",
    "open_date(5i)"=>"00", "notes"=>"123123", "private_notes"=>"0",
    "lock_version"=>"7"}, "time_entry"=>{"hours"=>"",
    "activity_id"=>"19", "comments"=>""}, "last_journal_id"=>"954",
    "commit"=>"Принять", "next_issue_id"=>"116", "issue_position"=>"1",
    "issue_count"=>"6", "id"=>"174"}//
    //  Current user: i.pushkin (id=5)//
    //Completed 500 Internal Server Error in 42ms (ActiveRecord: 6.9ms)//
    //
    //NoMethodError (undefined method `slice' for nil:NilClass)://
    //plugins/redmine_issue_open_date/lib/issue_open_date/hook_listener.rb:24:in
    `block in assign_issue_attributes'//
    //plugins/redmine_issue_open_date/lib/issue_open_date/hook_listener.rb:23:in
    `assign_issue_attributes'//
    //plugins/redmine_issue_open_date/lib/issue_open_date/hook_listener.rb:8:in
    `controller_issues_edit_before_save'//
    //  lib/redmine/hook.rb:61:in `block (2 levels) in call_hook'//
    //  lib/redmine/hook.rb:61:in `each'//
    //  lib/redmine/hook.rb:61:in `block in call_hook'//
    //  lib/redmine/hook.rb:58:in `tap'//
    //  lib/redmine/hook.rb:58:in `call_hook'//
    //  lib/redmine/hook.rb:91:in `call_hook'//
    //  app/controllers/issues_controller.rb:563:in `block in
    save_issue_with_child_records'//
    //  app/controllers/issues_controller.rb:552:in
    `save_issue_with_child_records'//
    //  app/controllers/issues_controller.rb:169:in `update'//
    //  lib/redmine/sudo_mode.rb:63:in `sudo_mode'/

13 Nov 2019 21:48, Igor Olemskoi пишет:

**Comment by ikuchugov** [comment]
Аналогичная проблема. Ubuntu и Nginx
Environment:
  Redmine version                3.4.10.stable.18058
  Ruby version                   2.5.1-p57 (2018-03-29) [x86_64-linux-gnu]
  Rails version                  4.2.11.1
  Environment                    production
  Database adapter               Mysql2
SCM:
  Subversion                     1.9.7
  Git                            2.17.1
  Filesystem               

При попытке изменить любую задачу в Production.log:
 Started PATCH "/redmine/issues/3727" for x.x.x.x at 2019-12-24 13:20:20 +0300
Processing by IssuesController#update as HTML
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"nbIO7IjvqkVTSeVx+yXgPyTE9mkYvanyV7fDLTE9QqdExlrp9u1TQJXb00XU13D8F1Fit5eg5n/5kiqMGQ+jMA==", "form_update_triggered_by"=>"", "issue"=>{"is_private"=>"0", "project_id"=>"1", "author_id"=>"1", "tracker_id"=>"1", "subject"=>"Test", "description"=>"", "status_id"=>"2", "priority_id"=>"3", "assigned_to_id"=>"1", "parent_issue_id"=>"", "start_date"=>"2019-10-11", "due_date"=>"", "estimated_hours"=>"", "custom_field_values"=>{"7"=>""}, "notes"=>"", "private_notes"=>"0", "lock_version"=>"2"}, "new_checklist"=>"", "time_entry"=>{"hours"=>"", "activity_id"=>"", "comments"=>""}, "last_journal_id"=>"22145", "commit"=>"Принять", "issue_position"=>"1", "issue_count"=>"1", "id"=>"3727"}
  Current user: redmine (id=1)
Completed 500 Internal Server Error in 84ms (ActiveRecord: 13.8ms)

NoMethodError (undefined method `slice' for nil:NilClass):
  plugins/redmine_issue_open_date/lib/issue_open_date/hook_listener.rb:24:in `block in assign_issue_attributes'
  plugins/redmine_issue_open_date/lib/issue_open_date/hook_listener.rb:23:in `assign_issue_attributes'
  plugins/redmine_issue_open_date/lib/issue_open_date/hook_listener.rb:8:in `controller_issues_edit_before_save'
  lib/redmine/hook.rb:61:in `block (2 levels) in call_hook'
  lib/redmine/hook.rb:61:in `each'
  lib/redmine/hook.rb:61:in `block in call_hook'
  lib/redmine/hook.rb:58:in `tap'
  lib/redmine/hook.rb:58:in `call_hook'
  lib/redmine/hook.rb:91:in `call_hook'
  app/controllers/issues_controller.rb:563:in `block in save_issue_with_child_records'
  app/controllers/issues_controller.rb:552:in `save_issue_with_child_records'
  app/controllers/issues_controller.rb:169:in `update'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'

**Comment by pipneogen** [comment]
Год почти прошёл, есть какие-то идеи?

**Comment by pipneogen** [comment]
Проблема пропала с последними обновлениями
